travis:
  secure:
    BINSTAR_TOKEN: AiDRr69iqcvJnB5QAA35QM1awkChDNIkVwHd5TCmKJSObGYQjPKvvSRrN+I9RCDIfE+CY5lJfHyjVSZmblVYH8LWbp+CYPCGn3NWP7b237ZXR+biKCJaVo580s3OR4nDZlNgeIbBzn6LRy/JRDa+hh5N9ODhMmU02m/xD6vDn+L9ut7Hkrj9GDk9nfsxtPMPhiqVnbt8a/An0xPzuzz8ud613kuu6FxIA90uHzPC+5/inPwoXT/92fe76wkjHq1tz+sSZUy+UFa8a2gOv8LxaCTCcqslMxdrY9E+ovGwoh1ZB4dJFEK2D0F7esbKsKRZ4llrJNSEiWwL6oEJiz+zsiHaA4y9NjL8DDcc9evdV9419tqPhcj9YcnU0fs+tKL/EGMUFsw8hEg9gLZnF2GqEbS6f4e3phKSKaASftW4hdEBwMeEtbpEZnSEeYVb3jpMXBLFzJvt10rkBHzuYcju5iiItloSN4h3yAAr9NB8DGtB15ac+4hhaItZs6KTgmGTLz5LYliB/KE1VJO/VOztyInE0SW6KEcsBChFzCYH6JV4YyKYMe95Vm2ChjfAP0UyKESMr2dYMF3kUSS3dfDn8PX2Kjbcg1IrBYrcjBG++ESWyTbATVc8X/gx8RHqTh2bA0GLeOzf5gH7LzFcf2AOq34o/NkTHhiqtur7A4oj7u0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
